backend:
  name: git-gateway

i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: true
      - label: "featuredImage"
        name: "featuredImage"
        widget: "image"
        i18n: duplicate
      - label: "Author"
        name: "author"
        widget: "string"
        i18n: duplicate
      - label: "Published At"
        name: "publishedAt"
        widget: "datetime"
        i18n: duplicate
      - label: "Summary"
        name: "summary"
        widget: "string"
        i18n: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        i18n: true
